Add option for FileManagerStrategy discard stale data
aws-robotics/cloudwatchlogs-ros1 pull request #64
Opened 2020-09-09 21:04 UTC by jikawa-az

Related to #56 for Cloudwatch-common

Signed-off-by: Jesse Ikawa <jikawa@amazon.com>

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

2020-09-09 21:15 UTC, jikawa-az commented
The Travis builds currently do not pass since FileManagerStrategyOptions has not been updated with the new discard_stale_data option from cloudwatch-common PR.

2020-09-09 21:23 UTC, dabonnie requested changes
Can you please add a [unit test(s)](https://github.com/aws-robotics/cloudwatchlogs-ros1/blob/master/cloudwatch_logger/test/log_node_param_helper_test.cpp) for the new parameter?

2020-09-09 21:23 UTC, dabonnie commented on README.md
> +| discard_stale_data | Whether or not to discard log batch data that are over 14 days old, which are rejected by AWS PutLogEvents. | *bool* | true/false | false |
```suggestion
| discard_stale_data | Whether or not to discard log batch data that are over 14 days old, which are rejected by [AWS PutLogEvents](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutLogEvents.html). | *bool* | true/false | false |
```

2020-09-09 21:23 UTC, dabonnie commented on cloudwatch_logger/config/sample_configuration.yaml
> +# whether or not to automatically discard log data > 14 days old
```suggestion
# whether or not to automatically delete log data > 14 days old
```

2020-09-09 21:23 UTC, dabonnie commented on README.md
> +| discard_stale_data | Whether or not to discard log batch data that are over 14 days old, which are rejected by AWS PutLogEvents. | *bool* | true/false | false |
```suggestion
| delete_stale_data | Whether or not to delete log batch data that are over 14 days old, which are rejected by AWS PutLogEvents. | *bool* | true/false | false |
```

Let's make it clear that log data over 14 days old will never be uploaded and this flag deletes the data from disk (if it was read from disk).

2020-09-09 21:23 UTC, dabonnie commented on cloudwatch_logger/config/sample_configuration.yaml
> +discard_stale_data: false
```suggestion
delete_stale_data: false
```

2020-09-10 19:34 UTC, dabonnie approved these changes

2020-09-10 20:36 UTC, merged